/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package joption;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author My PC
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        
        ImageIcon icon = new ImageIcon("C:\\Users\\Administrator\\Documents\\NetBeansProjects\\BookBorrowingSystem\\src\\resources\\Images\\JLibraryLogo.png");
setIconImage(icon.getImage());
        
        setSize(800, 640);
         setLocationRelativeTo(null);
         addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                JFrame frame = (JFrame) e.getSource();
                
                int result = JOptionPane.showConfirmDialog(
                        frame,
                        "Are you sure you want to close the window?",
                        "Confirm Exit",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.WARNING_MESSAGE
                );

                if (result == JOptionPane.YES_OPTION) {
                    frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                } else {
                    frame.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE); 
                }
                }
                 });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homeAdminButton = new javax.swing.JButton();
        homeUserButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        companyLogo = new javax.swing.JLabel();
        companyDescription = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        homeBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HOME");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homeAdminButton.setBackground(new java.awt.Color(242, 242, 242));
        homeAdminButton.setFont(new java.awt.Font("Bahnschrift", 1, 36)); // NOI18N
        homeAdminButton.setForeground(new java.awt.Color(111, 79, 55));
        homeAdminButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Administrator\\Documents\\NetBeansProjects\\BookBorrowingSystem\\src\\resources\\Images\\adminIcon.png")); // NOI18N
        homeAdminButton.setText("Admin");
        homeAdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeAdminButtonActionPerformed(evt);
            }
        });
        getContentPane().add(homeAdminButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 430, 310, 50));

        homeUserButton.setBackground(new java.awt.Color(242, 242, 242));
        homeUserButton.setFont(new java.awt.Font("Bahnschrift", 1, 36)); // NOI18N
        homeUserButton.setForeground(new java.awt.Color(111, 79, 55));
        homeUserButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Administrator\\Documents\\NetBeansProjects\\BookBorrowingSystem\\src\\resources\\Images\\userIcon.png")); // NOI18N
        homeUserButton.setText("User");
        homeUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeUserButtonActionPerformed(evt);
            }
        });
        getContentPane().add(homeUserButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 320, 50));

        jPanel1.setBackground(new java.awt.Color(111, 79, 55));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        companyLogo.setBackground(new java.awt.Color(255, 255, 255));
        companyLogo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Administrator\\Documents\\NetBeansProjects\\BookBorrowingSystem\\src\\resources\\Images\\companyLogoWhiteVersion.png")); // NOI18N
        jPanel1.add(companyLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 12, 268, 110));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Bahnschrift", 1, 15)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("\tWelcome to Jlibrary Borrow & Sell, your gateway to endless knowledge and \nadventure! Dive into a vast collection of books. Whether you're seeking the latest bestseller, \nexploring new ideas, or finding a quiet spot to study, our library offers a warm and inviting \nspace for all. Join us for exciting events, workshops, and community programs that inspire \ncreativity and connection. Discover the joy of reading and learning—your next great \nadventure awaits!\n\nReady to read?");
        jTextArea1.setToolTipText("");
        companyDescription.setViewportView(jTextArea1);

        jPanel1.add(companyDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 661, 173));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 700, 330));

        homeBackground.setIcon(new javax.swing.ImageIcon("C:\\Users\\Administrator\\Documents\\NetBeansProjects\\BookBorrowingSystem\\src\\resources\\Images\\homebackground.jpg")); // NOI18N
        getContentPane().add(homeBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeAdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeAdminButtonActionPerformed
       loginAdmin loginAdmin = new loginAdmin();
       loginAdmin.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_homeAdminButtonActionPerformed

    private void homeUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeUserButtonActionPerformed
       loginUser loginUser = new loginUser();
       loginUser.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_homeUserButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("FlatlafLight".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane companyDescription;
    private javax.swing.JLabel companyLogo;
    private javax.swing.JButton homeAdminButton;
    private javax.swing.JLabel homeBackground;
    private javax.swing.JButton homeUserButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
