/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package joption;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author My PC
 */
public class loginUser extends javax.swing.JFrame {
    private Connection con;
    private int userID;

    /**
     * Creates new form loginUser
     */
    public loginUser() {
        initComponents();
        setSize(800, 640);
        setLocationRelativeTo(null);
        
        ImageIcon icon = new ImageIcon("C:\\Users\\Administrator\\Documents\\NetBeansProjects\\BookBorrowingSystem\\src\\resources\\Images\\JLibraryLogo.png");
setIconImage(icon.getImage());
    }

    public void Connect() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/joption","root","");
            
        } catch(ClassNotFoundException ex) {
            Logger.getLogger(loginAdmin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(loginAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginUserPanel = new javax.swing.JPanel();
        loginUserIcon = new javax.swing.JLabel();
        loginUserUsernameLabel = new javax.swing.JLabel();
        loginUserUsernameField = new javax.swing.JTextField();
        loginUserPasswordLabel = new javax.swing.JLabel();
        loginPasswordField = new javax.swing.JPasswordField();
        seePasswordCheckBox = new javax.swing.JCheckBox();
        dontHaveAnAccountLabel = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        signUpButton = new javax.swing.JButton();
        backHomeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("LOGIN USER");
        setSize(new java.awt.Dimension(800, 600));

        loginUserPanel.setBackground(new java.awt.Color(111, 79, 55));
        loginUserPanel.setMinimumSize(new java.awt.Dimension(800, 600));
        loginUserPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginUserIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Administrator\\Documents\\NetBeansProjects\\BookBorrowingSystem\\src\\resources\\Images\\loginIcon.jpg")); // NOI18N
        loginUserIcon.setText("jLabel4");
        loginUserPanel.add(loginUserIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(-120, -240, 390, 1310));

        loginUserUsernameLabel.setFont(new java.awt.Font("Bahnschrift", 1, 36)); // NOI18N
        loginUserUsernameLabel.setForeground(new java.awt.Color(255, 255, 255));
        loginUserUsernameLabel.setText("Username:");
        loginUserPanel.add(loginUserUsernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, -1, -1));

        loginUserUsernameField.setFont(new java.awt.Font("Bahnschrift", 1, 30)); // NOI18N
        loginUserUsernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginUserUsernameFieldActionPerformed(evt);
            }
        });
        loginUserPanel.add(loginUserUsernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 422, 59));

        loginUserPasswordLabel.setFont(new java.awt.Font("Bahnschrift", 1, 36)); // NOI18N
        loginUserPasswordLabel.setForeground(new java.awt.Color(255, 255, 255));
        loginUserPasswordLabel.setText("Password:");
        loginUserPanel.add(loginUserPasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, -1, -1));

        loginPasswordField.setFont(new java.awt.Font("Bahnschrift", 1, 30)); // NOI18N
        loginPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginPasswordFieldActionPerformed(evt);
            }
        });
        loginUserPanel.add(loginPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 422, 59));

        seePasswordCheckBox.setBackground(new java.awt.Color(111, 79, 55));
        seePasswordCheckBox.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        seePasswordCheckBox.setForeground(new java.awt.Color(255, 255, 255));
        seePasswordCheckBox.setText("See password");
        seePasswordCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seePasswordCheckBoxActionPerformed(evt);
            }
        });
        loginUserPanel.add(seePasswordCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 164, 34));

        dontHaveAnAccountLabel.setFont(new java.awt.Font("Bahnschrift", 2, 18)); // NOI18N
        dontHaveAnAccountLabel.setForeground(new java.awt.Color(255, 255, 255));
        dontHaveAnAccountLabel.setText("Don't have a user account?");
        loginUserPanel.add(dontHaveAnAccountLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 570, 264, -1));

        loginButton.setBackground(new java.awt.Color(111, 79, 55));
        loginButton.setFont(new java.awt.Font("Bahnschrift", 1, 36)); // NOI18N
        loginButton.setForeground(new java.awt.Color(255, 255, 255));
        loginButton.setText("LOG IN");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        loginUserPanel.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, 410, -1));

        signUpButton.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        signUpButton.setForeground(new java.awt.Color(111, 79, 55));
        signUpButton.setText("Sign Up");
        signUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpButtonActionPerformed(evt);
            }
        });
        loginUserPanel.add(signUpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 560, -1, -1));

        backHomeButton.setBackground(new java.awt.Color(111, 79, 55));
        backHomeButton.setFont(new java.awt.Font("Bahnschrift", 1, 36)); // NOI18N
        backHomeButton.setForeground(new java.awt.Color(255, 255, 255));
        backHomeButton.setText("Back");
        backHomeButton.setFocusable(false);
        backHomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backHomeButtonActionPerformed(evt);
            }
        });
        loginUserPanel.add(backHomeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, 160, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginUserPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginUserPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void seePasswordCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seePasswordCheckBoxActionPerformed
        if (seePasswordCheckBox.isSelected()) {
            loginPasswordField.setEchoChar((char) 0);
        } else {
            loginPasswordField.setEchoChar('*');
        }
    }//GEN-LAST:event_seePasswordCheckBoxActionPerformed

    private void signUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpButtonActionPerformed
        signupUser signupUser = new signupUser();
        signupUser.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_signUpButtonActionPerformed

    private void backHomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backHomeButtonActionPerformed
        Home Home = new Home();
        Home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backHomeButtonActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        String username = loginUserUsernameField.getText().trim();
    String password = new String(loginPasswordField.getPassword()).trim();

    if (username.isEmpty() || password.isEmpty()) {
        JOptionPane.showMessageDialog(this, "All fields are required!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    try {
        // Establish connection if not already connected
        if (con == null || con.isClosed()) {
            Connect();
        }

        String query = "SELECT * FROM user WHERE username = ? AND password = ?";
        java.sql.PreparedStatement pst = con.prepareStatement(query);
        pst.setString(1, username);
        pst.setString(2, password);

        java.sql.ResultSet rs = pst.executeQuery();

        if (rs.next()) {
            int userID = rs.getInt("userID"); // Ensure "userID" matches the column name in your database
            String dbname = rs.getString("name");

            // Set the current user ID in the SessionManager
            SessionManager.setCurrentUserID(userID);

            // Login successful
            JOptionPane.showMessageDialog(this, "Login Successful. Hello " + dbname + "!", "Success", JOptionPane.INFORMATION_MESSAGE);

            // Open the UserDashboard
            UserDashboard userDashboard = new UserDashboard();
            userDashboard.setVisible(true);
            userDashboard.setLocationRelativeTo(null);
            this.dispose(); // Close the login form
        } else {
            // Login failed
            JOptionPane.showMessageDialog(this, "Invalid credentials. There might be a mistake in one of the fields. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
        }

        rs.close(); // Always close the ResultSet
        pst.close(); // Always close the PreparedStatement

    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Database error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
    }   
    }//GEN-LAST:event_loginButtonActionPerformed

    private void loginUserUsernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginUserUsernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginUserUsernameFieldActionPerformed

    private void loginPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginPasswordFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Flatlaf".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backHomeButton;
    private javax.swing.JLabel dontHaveAnAccountLabel;
    private javax.swing.JButton loginButton;
    private javax.swing.JPasswordField loginPasswordField;
    private javax.swing.JLabel loginUserIcon;
    private javax.swing.JPanel loginUserPanel;
    private javax.swing.JLabel loginUserPasswordLabel;
    private javax.swing.JTextField loginUserUsernameField;
    private javax.swing.JLabel loginUserUsernameLabel;
    private javax.swing.JCheckBox seePasswordCheckBox;
    private javax.swing.JButton signUpButton;
    // End of variables declaration//GEN-END:variables
}
