package joption;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author My PC
 */
public class loginAdmin extends javax.swing.JFrame {
    private Connection con;
    private int adminID;

    /**
     * Creates new form loginAdmin
     */
    public loginAdmin() {
        initComponents();
        setSize(800, 640);
        setLocationRelativeTo(null);
        
        ImageIcon icon = new ImageIcon("C:\\Users\\Administrator\\Documents\\NetBeansProjects\\BookBorrowingSystem\\src\\resources\\Images\\JLibraryLogo.png");
setIconImage(icon.getImage());
    }
    
    public void Connect() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/joption","root","");
            
        } catch(ClassNotFoundException ex) {
            Logger.getLogger(loginAdmin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(loginAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginAdminPanel = new javax.swing.JPanel();
        loginAdminIcon = new javax.swing.JLabel();
        loginAdminUsernameLabel = new javax.swing.JLabel();
        loginAdminCodeField = new javax.swing.JTextField();
        loginAdminPasswordLabel = new javax.swing.JLabel();
        loginAdminPasswordField = new javax.swing.JPasswordField();
        seePasswordCheckBox = new javax.swing.JCheckBox();
        dontHaveAnAccountLabel = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        signUpButton = new javax.swing.JButton();
        backHomeButton = new javax.swing.JButton();
        loginAdminCodeLabel = new javax.swing.JLabel();
        loginAdminUsernameField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("LOGIN ADMIN");

        loginAdminPanel.setBackground(new java.awt.Color(111, 79, 55));
        loginAdminPanel.setMinimumSize(new java.awt.Dimension(0, 0));
        loginAdminPanel.setPreferredSize(new java.awt.Dimension(800, 600));
        loginAdminPanel.setRequestFocusEnabled(false);
        loginAdminPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginAdminIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Administrator\\Documents\\NetBeansProjects\\BookBorrowingSystem\\src\\resources\\Images\\loginIcon.jpg")); // NOI18N
        loginAdminIcon.setText("jLabel4");
        loginAdminPanel.add(loginAdminIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(-130, -250, 390, 1310));

        loginAdminUsernameLabel.setFont(new java.awt.Font("Bahnschrift", 1, 36)); // NOI18N
        loginAdminUsernameLabel.setForeground(new java.awt.Color(255, 255, 255));
        loginAdminUsernameLabel.setText("Name:");
        loginAdminPanel.add(loginAdminUsernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, -1, -1));

        loginAdminCodeField.setFont(new java.awt.Font("Bahnschrift", 1, 30)); // NOI18N
        loginAdminPanel.add(loginAdminCodeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 422, 59));

        loginAdminPasswordLabel.setFont(new java.awt.Font("Bahnschrift", 1, 36)); // NOI18N
        loginAdminPasswordLabel.setForeground(new java.awt.Color(255, 255, 255));
        loginAdminPasswordLabel.setText("Password:");
        loginAdminPanel.add(loginAdminPasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, -1, -1));

        loginAdminPasswordField.setFont(new java.awt.Font("Bahnschrift", 1, 30)); // NOI18N
        loginAdminPanel.add(loginAdminPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, 422, 59));

        seePasswordCheckBox.setBackground(new java.awt.Color(111, 79, 55));
        seePasswordCheckBox.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        seePasswordCheckBox.setForeground(new java.awt.Color(255, 255, 255));
        seePasswordCheckBox.setText("See password");
        seePasswordCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seePasswordCheckBoxActionPerformed(evt);
            }
        });
        loginAdminPanel.add(seePasswordCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, 130, 34));

        dontHaveAnAccountLabel.setFont(new java.awt.Font("Bahnschrift", 2, 18)); // NOI18N
        dontHaveAnAccountLabel.setForeground(new java.awt.Color(255, 255, 255));
        dontHaveAnAccountLabel.setText("Don't have an admin account?");
        loginAdminPanel.add(dontHaveAnAccountLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 560, 330, -1));

        loginButton.setBackground(new java.awt.Color(111, 79, 55));
        loginButton.setFont(new java.awt.Font("Bahnschrift", 1, 36)); // NOI18N
        loginButton.setForeground(new java.awt.Color(255, 255, 255));
        loginButton.setText("LOG IN");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        loginAdminPanel.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 450, 420, -1));

        signUpButton.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        signUpButton.setForeground(new java.awt.Color(111, 79, 55));
        signUpButton.setText("Sign Up");
        signUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpButtonActionPerformed(evt);
            }
        });
        loginAdminPanel.add(signUpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 550, -1, -1));

        backHomeButton.setBackground(new java.awt.Color(111, 79, 55));
        backHomeButton.setFont(new java.awt.Font("Bahnschrift", 1, 36)); // NOI18N
        backHomeButton.setForeground(new java.awt.Color(255, 255, 255));
        backHomeButton.setText("Back");
        backHomeButton.setFocusable(false);
        backHomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backHomeButtonActionPerformed(evt);
            }
        });
        loginAdminPanel.add(backHomeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, 160, 50));

        loginAdminCodeLabel.setFont(new java.awt.Font("Bahnschrift", 1, 36)); // NOI18N
        loginAdminCodeLabel.setForeground(new java.awt.Color(255, 255, 255));
        loginAdminCodeLabel.setText("Code:");
        loginAdminPanel.add(loginAdminCodeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, -1, -1));

        loginAdminUsernameField.setFont(new java.awt.Font("Bahnschrift", 1, 30)); // NOI18N
        loginAdminPanel.add(loginAdminUsernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 422, 59));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginAdminPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginAdminPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpButtonActionPerformed
       signupAdmin signupAdmin = new signupAdmin();
       signupAdmin.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_signUpButtonActionPerformed

    private void backHomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backHomeButtonActionPerformed
       Home Home = new Home();
       Home.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_backHomeButtonActionPerformed

    private void seePasswordCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seePasswordCheckBoxActionPerformed
        if (seePasswordCheckBox.isSelected()) {
            loginAdminPasswordField.setEchoChar((char) 0);
        } else {
            loginAdminPasswordField.setEchoChar('*');
            }
    }//GEN-LAST:event_seePasswordCheckBoxActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        String adminCode = loginAdminCodeField.getText().trim();
        String name = loginAdminUsernameField.getText().trim();
        String password = new String(loginAdminPasswordField.getPassword()).trim();

        if (adminCode.isEmpty() || name.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "All fields are required!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            // Establish connection if not already connected
            if (con == null || con.isClosed()) {
                Connect();
            }

            String query = "SELECT * FROM admin WHERE adminCode = ? AND name = ? AND password = ?";
            java.sql.PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, adminCode);
            pst.setString(2, name);
            pst.setString(3, password);

            java.sql.ResultSet rs = pst.executeQuery();

            System.out.println("Admin Code: " + adminCode);
            System.out.println("Name: " + name);
            System.out.println("Password: " + password);

            if (rs.next()) {
                this.adminID = rs.getInt("adminID"); // Ensure "adminID" matches the column name in your database
                String dbname = rs.getString("name");
                // Login successful
                JOptionPane.showMessageDialog(this, "Login Successful. Hello " + dbname + "! ", "Success", JOptionPane.INFORMATION_MESSAGE);
                AdminDashboard admin = new AdminDashboard();
                admin.setVisible(true);
                admin.setLocationRelativeTo(null);
                // You can redirect the user to the admin panel here
                this.dispose(); // Close the login form
            } else {
                // Login failed
                JOptionPane.showMessageDialog(this, "Invalid credentials. There might be a mistake in one of the fields. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
            }

            rs.close(); // Always close the ResultSet
            pst.close(); // Always close the PreparedStatement

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Database error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Flatlaf".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backHomeButton;
    private javax.swing.JLabel dontHaveAnAccountLabel;
    private javax.swing.JTextField loginAdminCodeField;
    private javax.swing.JLabel loginAdminCodeLabel;
    private javax.swing.JLabel loginAdminIcon;
    private javax.swing.JPanel loginAdminPanel;
    private javax.swing.JPasswordField loginAdminPasswordField;
    private javax.swing.JLabel loginAdminPasswordLabel;
    private javax.swing.JTextField loginAdminUsernameField;
    private javax.swing.JLabel loginAdminUsernameLabel;
    private javax.swing.JButton loginButton;
    private javax.swing.JCheckBox seePasswordCheckBox;
    private javax.swing.JButton signUpButton;
    // End of variables declaration//GEN-END:variables
}
